# Generated by Django 5.1.4 on 2025-02-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_gradient_end',
            field=models.CharField(default='#2a475e', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_gradient_start',
            field=models.CharField(default='#1b2838', max_length=7),
        ),
    ]
