# Generated by Django 5.1.4 on 2025-02-22 19:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_profile_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to=accounts.models.user_profile_photo_path),
        ),
    ]
