# Generated by Django 5.1.4 on 2025-02-27 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_gamestatistics_playerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='computer_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamestatistics',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
