# Generated by Django 5.1.4 on 2025-03-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_playerstats_win_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='users/avatars/default_avatar.jpg', upload_to='users/avatars/', verbose_name='Avatar'),
        ),
    ]
