# Generated by Django 5.1.4 on 2025-03-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='users/avatars/default_avatar.jpg', null=True, upload_to='users/avatars/', verbose_name='Avatar'),
        ),
    ]
