# Generated by Django 5.1.4 on 2025-02-17 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_gameinvite_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gameinvite',
            name='chat_gamein_sender__a32b23_idx',
        ),
        migrations.AlterUniqueTogether(
            name='gameinvite',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='gameinvite',
            index=models.Index(fields=['sender', 'recipient', 'status', 'timestamp'], name='chat_gamein_sender__34218a_idx'),
        ),
    ]
