# Generated by Django 5.1.4 on 2025-03-02 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_gameinvite_chat_gamein_sender__a32b23_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
