# Generated by Django 5.1.4 on 2025-03-21 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_userprofile_blocked_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
